# -*- coding: utf-8 -*-
"""ODI_Generation_analysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VKaOPM7LSXQZ56PB0UwF2o4grp4U-r0p
"""

import pandas as pd

df = pd.read_csv("/content/temp.csv")
df.head()

df = df.drop(['8','12'],axis=1)
df

df.columns =  ["Name","Runs","Minutes","Balls","Fours","Sixes","Strike_Rate","Innings","Opposition","Venue","Date"]
df

df = df[df["Runs"]!="DNB"]
df

df = df[df["Runs"]!="TDNB"]
df

df = df[df["Runs"]!="absent"]
df

df = df[df["Runs"]!="sub"]
df

year = []
for index, row in df.iterrows():
  year_row = "20" + row["Date"][-2:]
  year.append(year_row)

len(year)

df["Year"] = year
df

df.info()

for index, row in df.iterrows():
  if(row["Runs"][-1]=="*"):
    runs = int(row["Runs"][:-1])
  else:
    runs = int(row["Runs"])
  df.loc[index,"Runs"] = runs

df

hundred = []
for index, row in df.iterrows():
  if(row["Runs"]>=100):
    hundred.append(1)
  else:
    hundred.append(0)

df["Century"] = hundred

df

for index, row in df.iterrows():
  df.loc[index,"Balls"] = int(row["Balls"])
  df.loc[index,"Fours"] = int(row["Fours"])
  df.loc[index,"Sixes"] = int(row["Sixes"])

df

df["Runs"] = pd.to_numeric(df["Runs"])
df["Balls"] = pd.to_numeric(df["Balls"])
df["Fours"] = pd.to_numeric(df["Fours"])
df["Sixes"] = pd.to_numeric(df["Sixes"])

df = df[df["Balls"]>0]
df

df["Strike_Rate"] = pd.to_numeric(df["Strike_Rate"])

grped_data = df.groupby(["Year"])

mean = grped_data.mean()
mean

"""Average Runs per Innings year wise"""

import matplotlib.pyplot as plt
plt.scatter(mean.index , mean["Runs"])

plt.scatter(mean.index , mean["Sixes"])

plt.scatter(mean.index , mean["Century"])

plt.scatter(mean.index , mean["Strike_Rate"])

plt.scatter(mean.index , mean["Balls"])

